#!/usr/bin/env node
// Generates the styles ChaiBuilder needs before `next build` / `next dev`. One script, two steps:
//
// 1. Embedded Tailwind stylesheets (pro source checkouts only)
//    The runtime page-CSS compiler (src/tailwind/v4.ts) compiles from embedded copies of
//    Tailwind v4's stylesheets instead of reading node_modules at runtime — filesystem reads
//    break on serverless hosts (files aren't traced into the function bundle). This step
//    regenerates src/tailwind/stylesheets.generated.ts from the installed tailwindcss so the
//    embedded copies track version bumps. Skipped automatically when the pro source tree isn't
//    present (i.e. in projects consuming the published dist, which already bundles them).
//
// 2. public/chaistyles.css — the page-style dedup reference
//    The page-style compiler strips every rule already present in this file, so a published page
//    only inlines the CSS its blocks add on top of the global stylesheet. It must be generated
//    from the same input Next.js compiles so its selectors match what ships to the browser.
//    Output is intentionally NOT minified: minification merges selectors (`.a,.b{...}`), which
//    would break the exact-selector matching the dedup filter relies on.
//
// Usage: generate-styles [--input <css file>] [--output <css file>]
//   --input   global stylesheet to compile (default: src/app/(frontend)/public.css)
//   --output  dedup reference to write     (default: public/chaistyles.css)
import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = process.cwd();
const require = createRequire(path.join(projectRoot, "package.json"));

const readArg = (name, fallback) => {
  const index = process.argv.indexOf(name);
  return index !== -1 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
};

// --- Step 1: embed Tailwind v4 stylesheets into the pro source tree (when present) ---

const embedTailwindStylesheets = async () => {
  const output = path.resolve(scriptDir, "../src/tailwind/stylesheets.generated.ts");

  if (!existsSync(path.dirname(output))) {
    return; // dist consumer — embedded stylesheets ship inside the published bundle
  }

  const version = require("tailwindcss/package.json").version;
  const read = async (id) => fs.readFile(require.resolve(id), "utf8");

  const [index, theme, preflight, utilities] = await Promise.all([
    read("tailwindcss/index.css"),
    read("tailwindcss/theme.css"),
    read("tailwindcss/preflight.css"),
    read("tailwindcss/utilities.css"),
  ]);

  const escape = (css) => css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

  const content = `// GENERATED FILE — do not edit by hand.
// Embedded copies of Tailwind CSS v${version}'s stylesheets, inlined so the runtime page-CSS
// compiler needs no filesystem access (required for serverless deploys and for consumer
// projects to work without host-specific tracing config).
// Regenerated by scripts/generate-styles.mjs, which runs before build/dev.

export const TAILWIND_VERSION = "${version}";

export const TAILWIND_STYLESHEETS: Record<string, string> = {
  "index.css": \`${escape(index)}\`,
  "theme.css": \`${escape(theme)}\`,
  "preflight.css": \`${escape(preflight)}\`,
  "utilities.css": \`${escape(utilities)}\`,
};
`;

  const previous = await fs.readFile(output, "utf8").catch(() => null);
  if (previous === content) {
    console.log(`[chai-styles] embedded tailwind stylesheets up to date (v${version})`);
  } else {
    await fs.writeFile(output, content);
    console.log(`[chai-styles] embedded tailwind stylesheets (v${version})`);
  }
};

// --- Step 2: compile the global stylesheet to the chaistyles dedup reference ---

const generateChaistyles = async () => {
  const input = path.resolve(projectRoot, readArg("--input", "src/app/(frontend)/public.css"));
  const output = path.resolve(projectRoot, readArg("--output", "public/chaistyles.css"));

  if (!existsSync(input)) {
    console.warn(`[chai-styles] skipped chaistyles: input not found (${path.relative(projectRoot, input)})`);
    return;
  }

  const [{ default: postcss }, { default: tailwindcss }] = await Promise.all([
    import(require.resolve("postcss")),
    import(require.resolve("@tailwindcss/postcss")),
  ]);

  const css = await fs.readFile(input, "utf8");
  const result = await postcss([tailwindcss({ optimize: false })]).process(css, {
    from: input,
    to: output,
  });

  await fs.mkdir(path.dirname(output), { recursive: true });
  await fs.writeFile(output, result.css);
  console.log(`[chai-styles] wrote ${path.relative(projectRoot, output)} (${(result.css.length / 1024).toFixed(1)} kB)`);
};

await embedTailwindStylesheets();
await generateChaistyles();
